### ISSUE TITLE
Migrate to MIT license

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/igloo#59]
Currently the project code is licensed under the [Apache 2.0][apache] license. This often causes problems when developers want to use the project or code parts of it in another project licensed under a less restricted license.

The project should migrate to the [MIT license][cal-mit] which is more open, unrestricted and the most used license for open source projects like [React][react] which has also recently been [re-licensed][pr].

### Tasks

* [x] Update all license SVG badges
* [x] Update the `LICENSE.md` content
* [x] Update- and simplify all source code comment header

[apache]: http://www.apache.org/licenses/LICENSE-2.0
[cal-mit]: https://choosealicense.com/licenses/mit/
[pr]: https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
[react]: https://reactjs.org
